### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [ty2u/spawner#36]
timings
https://timings.aikar.co/?id=99b9ab2c1abe4dbea62a68ddb2d20342

logs
```
[21:06:27] [Server thread/INFO]: [Spawner] Enabling Spawner v2.8.3-1603e95
[21:06:27] [Server thread/INFO]: [Spawner] Loading support for v1_12_R1
[21:06:27] [Server thread/WARN]: [Spawner] "Spawner v2.8.3-1603e95" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "private void me.ryvix.spawner.SpawnerEvents.onPlayerPickupItem(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [ryvix].
org.bukkit.plugin.AuthorNagException: null
	at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:277) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:545) [patched_1.12.2.jar:git-Paper-1222]
	at me.ryvix.spawner.Main.onEnable(Main.java:111) [Spawner.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1222]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1222]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by ty2u** [comment]
Thanks for the report, will fix that in the next release.

**Comment by mat41997** [comment]
^^ this is my sport : D
